### ISSUE TITLE
Nested @article{ in the bib format

### ISSUE THREAD

**Issue by dahyun-kang** [wookiekim/CorrespondentDream#1]
Thank you for releasing the code. Interesting work!

I just wanted to let you know a nested @article{ found in the bib format.

https://github.com/wookiekim/CorrespondentDream/blob/ec4f00f983a012922330ad57a8b0ed8388f14800/README.md?plain=1#L124

**Comment by wookiekim** [comment]
Thank you for pointing that out! It has been edited :)
